---
# configure node-stats for respondd 

- name: Clone node-stats repo for respondd.
  git:
    repo: https://github.com/FreiFunkMuenster/node-stats.git
    dest: /opt/node-stats
    version: glass_link
    force: yes

- name: Define cron for node-stats.
  cron:
    name: "node-stats"
    minute: "*"
    job: "/opt/node-stats/main.py -g /var/www/html/data/raw.json --yanic-raw -c /opt/node-stats/config.json >/dev/null 2>&1"

